name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  test:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    strategy:
      matrix:
        repo:
          - vulkan
          - wayland
          - X11
          - glfw
          - cimgui
          - spirv
          - glslang
          - shaderc
          - oniguruma
          - libjq
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo }}.zig"
        token: "${{ github.token }}"
    - uses: actions/checkout@v4
